### PR TITLE
Add LCD contrast support (90% accurately)

### PR DESCRIPTION
**Pull request by mckuhei**
Port from [my fork](https://github.com/mckuhei/Nuked-SC55)
I submitted it directly through github.dev. There may be errors in the code. Please point out if there are errors.
image
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by jcmoyer** [comment]
Since this touches core emulator functionality, I cannot verify whether or not it's correct. I would like to keep modifications to the backend to a minimum in order to make merging new commits from upstream easier. This is actually the reason I haven't bothered to clean up the backend yet, since I've been expecting the rather large upstream gui branch to be merged into master.

I recommend first trying to submit this PR upstream since one of the goals of this fork is to be behavior compatible with the original nuked-sc55. If they implement this feature differently in the future it creates more work here. That said, if nukeykt doesn't provide feedback or merge it in a reasonable timeframe, I'll reconsider.

**Comment by mckuhei** [comment]
I'm sorry that I can't create a new pull request because I've already forked the repository and made changes directly to the master branch. I will try to create a pull request to upstream later.

**Comment by mckuhei** [comment]
It seems that the only way to fork again is to create a new organization, but I don't want to create a new useless organization just to fork again.

**Comment by jcmoyer** [comment]
It's fine, I think the commits will stay here regardless of what you do now. I'll keep an eye on your upstream PR.

**Comment by mckuhei** [comment]
I have submitted a pull request upstream, please let me know if you need to reopen this pull request

**Pull request closed without merging**
